#!/usr/bin/env bash
# guard-generated-files.sh — PreToolUse hook (Edit | Write | NotebookEdit | Bash).
#
# cspell:ignore rmdir rsync shred alnum
#
# Two trees under src/database/ are GENERATED and must never be hand-edited:
#   • src/database/prisma/migrations/ — written by `prisma migrate dev`; the timestamped folder
#     names and their ordering define applied history. Hand edits corrupt the migration lineage.
#     Schema changes go through src/database/prisma/schema.prisma + the Prisma CLI.
#   • src/database/model/generated/ — the generated Prisma client output; regenerated by
#     `prisma generate` and overwritten on the next run.
#
# This hook hard-blocks two vectors:
#   • Edit / Write / NotebookEdit whose target path is inside a protected tree (the primary,
#     path-exact guard).
#   • Bash mutation of a protected path: rename/move/copy/delete/link verbs (mv, cp, rm, rmdir,
#     rename, ln, rsync, dd, truncate, tee, shred, unlink), git mv/rm/checkout/restore, in-place
#     editors (sed -i, perl -i), find with -delete/-exec, output redirection (`>`/`>>`/`>|`) into
#     a protected path, and `cd <protected-dir> && <destructive-verb>` (relative-arg deletes).
#
# The Bash branch is a strong net for the realistic shell vectors, not a complete sandbox — the
# Edit/Write path guard is the authoritative block. Prisma CLI commands (`prisma migrate dev`,
# `prisma generate`) do not name the protected paths, so they are unaffected.
#
# Emergency override (set ALLOW_GENERATED_FILE_MUTATION=1):
#   • inline prefix — `ALLOW_GENERATED_FILE_MUTATION=1 <cmd>` — leaves an audit trail in shell
#     history;
#   • exported in the launching shell — bypasses every subsequent call this session with NO
#     per-command trace, so prefer the inline form.

input=$(cat)
tool=$(printf '%s' "$input" | jq -r '.tool_name // ""')

# Matches a protected generated tree. The trailing class matches the dir terminated by `/`,
# whitespace, a quote, end-of-string, etc. — so a bare `.../migrations` (no trailing slash, e.g.
# `cd .../migrations`) still matches, without matching `migrations-notes`.
GEN_RE='database/(prisma/migrations|model/generated)([^[:alnum:]_]|$)'

# Parent-process bypass.
if [[ "${ALLOW_GENERATED_FILE_MUTATION:-}" == "1" ]]; then
  exit 0
fi

deny() {
  jq -n --arg r "$1" '{
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      permissionDecision: "deny",
      permissionDecisionReason: $r
    }
  }'
  exit 0
}

case "$tool" in
  Edit | Write | NotebookEdit | MultiEdit)
    target=$(printf '%s' "$input" | jq -r '.tool_input.file_path // .tool_input.notebook_path // ""')
    if printf '%s' "$target" | grep -qE "$GEN_RE"; then
      deny "Editing Prisma migrations or the generated model client is blocked — both are generated. Change src/database/prisma/schema.prisma and run the Prisma CLI (prisma migrate dev / prisma generate) instead. Emergency bypass: ALLOW_GENERATED_FILE_MUTATION=1."
    fi
    ;;
  Bash)
    cmd=$(printf '%s' "$input" | jq -r '.tool_input.command // ""')

    # Inline bypass — ONLY as a leading prefix of the whole command (the documented
    # `ALLOW_GENERATED_FILE_MUTATION=1 <cmd>` form), kept in shell history as an audit trail.
    # Matched with bash `[[ =~ ]]` against the raw command so `^` anchors to the START OF THE
    # STRING, not the start of any line — a token on a later line (or after `&&`/`;`) cannot
    # neutralize an earlier destructive segment.
    override_re='^[[:space:]]*ALLOW_GENERATED_FILE_MUTATION=1([[:space:]]|$)'
    if [[ "$cmd" =~ $override_re ]]; then
      exit 0
    fi

    # Fast pre-filter: nothing to weigh if no protected path is referenced.
    printf '%s\n' "$cmd" | grep -qE "$GEN_RE" || exit 0

    blocked=0
    # A protected path, matched loosely for use mid-argument. `seg` is "rest of the current
    # command segment" — chars up to the next separator (; & |) — so a mutating verb is only
    # flagged when the protected path is ITS argument, not merely co-present elsewhere on the
    # line. `rm /tmp/x; cat .../migrations/y` is therefore allowed (the rm targets /tmp/x; the
    # migration is only read).
    gen='database/(prisma/migrations|model/generated)'
    seg='[^;&|]*'

    # Output redirection (`>`, `>>`, `>|`) whose target token is a protected path. The target is
    # the single whitespace-delimited token after the redirect, so `cmd 2>&1` (target `&1`) and
    # `cmd > /tmp/out .../migrations/x` (target `/tmp/out`, protected path is a later read-arg)
    # do not trigger.
    if printf '%s\n' "$cmd" | grep -qE ">>?\|?[[:space:]]*[^[:space:];&|]*${gen}"; then
      blocked=1
    # rename / move / copy / delete / link verbs acting on a protected path
    elif printf '%s\n' "$cmd" | grep -qE "(^|[[:space:];&|(\`])(mv|cp|rm|rmdir|rename|ln|rsync|dd|truncate|tee|shred|unlink)[[:space:]]${seg}${gen}"; then
      blocked=1
    # git subcommands that move/delete/overwrite a tracked protected path
    elif printf '%s\n' "$cmd" | grep -qE "git[[:space:]]+(mv|rm|checkout|restore)[[:space:]]${seg}${gen}"; then
      blocked=1
    # in-place editors targeting a protected path
    elif printf '%s\n' "$cmd" | grep -qE "(sed[[:space:]]+-i|perl[[:space:]]+[^;&|]*-i)${seg}${gen}"; then
      blocked=1
    # find that deletes or executes against a protected tree
    elif printf '%s\n' "$cmd" | grep -qE "find[[:space:]]${seg}${gen}${seg}(-delete|-exec)"; then
      blocked=1
    # `cd <protected-dir> && <destructive-op> <relative>` — after cd-ing into a protected tree
    # the op's argument is relative and carries no path token, so the segment-keyed rules above
    # miss it. Catch cd-into-protected when the IMMEDIATELY-FOLLOWING segment is a destroyer
    # (same op set as above). Keying to the next segment avoids blocking an unrelated later op
    # (`cd … && echo hi && rm /tmp/x`), while the natural `cd … && rm -rf <folder>` is caught.
    # `cd … && ls` / `git status` / `cat` stay allowed.
    elif printf '%s\n' "$cmd" | grep -qE "(^|[[:space:];&|(\`])cd[[:space:]]${seg}${gen}${seg}[;&|]+[[:space:]]*((mv|cp|rm|rmdir|rename|ln|rsync|dd|truncate|tee|shred|unlink)([[:space:]]|$)|git[[:space:]]+(mv|rm|checkout|restore)[[:space:]]|sed[[:space:]]+-i|perl[[:space:]]+[^;&|]*-i|find[[:space:]][^;&|]*-(delete|exec))"; then
      blocked=1
    fi

    if [ "$blocked" -eq 1 ]; then
      deny "Renaming, moving, deleting, or rewriting Prisma migrations or the generated model client via shell is blocked — both are generated. Change src/database/prisma/schema.prisma and run the Prisma CLI instead. If a mutation is genuinely required, prefix it with ALLOW_GENERATED_FILE_MUTATION=1 (logged in shell history)."
    fi
    ;;
esac

exit 0
