export const SKILLS_ADMIN_TABLE_PAGE_SIZE = 16;
export const COURSES_ADMIN_TABLE_PAGE_SIZE = 16;
export const EXPERIENCES_ADMIN_TABLE_PAGE_SIZE = 8;
export const EDUCATIONS_ADMIN_TABLE_PAGE_SIZE = 8;
export const PROJECTS_ADMIN_TABLE_PAGE_SIZE = 8;
export const DETAILS_ADMIN_TABLE_PAGE_SIZE = 8;
