import jsdocPlugin from 'eslint-plugin-jsdoc';

/** @type {import('eslint').Linter.Config[]} */
export default [
  {
    plugins: {
      jsdoc: jsdocPlugin,
    },
    rules: {
      'jsdoc/check-alignment': 'error',
      'jsdoc/check-line-alignment': [
        'error',
        'never',
        { customSpacings: { postDelimiter: 1, postTag: 1, postType: 1 }, wrapIndent: '  ' },
      ],
      'jsdoc/check-tag-names': ['error', { definedTags: ['jest-environment'], enableFixer: true }],
      'jsdoc/empty-tags': 'error',
      'jsdoc/informative-docs': 'error',
      'jsdoc/lines-before-block': ['error', { checkBlockStarts: true, lines: 0 }],
      'jsdoc/match-description': [
        'error',
        {
          mainDescription: {
            match: /^\n?([A-Z`\d_][\s\S]*[.?!`]\s*)?$/.toString(),
            message: 'The description must begin with a capital letter and end with a period.',
          },
          tags: {
            deprecated: true,
            description: true,
            param: true,
            property: true,
            returns: true,
            summary: true,
            throws: true,
          },
        },
      ],
      'jsdoc/multiline-blocks': [
        'error',
        {
          noFinalLineText: true,
          noSingleLineBlocks: true,
          noZeroLineText: true,
          singleLineTags: ['type'],
        },
      ],
      'jsdoc/no-blank-blocks': ['error', { enableFixer: true }],
      'jsdoc/no-multi-asterisks': [
        'error',
        { allowWhitespace: false, preventAtEnd: true, preventAtMiddleLines: true },
      ],
      'jsdoc/require-description': ['error', { descriptionStyle: 'body' }],
      'jsdoc/require-hyphen-before-param-description': ['error', 'never'],
      'jsdoc/require-param-type': ['error', { contexts: ['any'] }],
      'jsdoc/require-property-type': 'error',
      'jsdoc/require-returns-type': ['error', { contexts: ['any'] }],
      'jsdoc/sort-tags': [
        'error',
        {
          linesBetween: 1,
          tagSequence: [
            { tags: ['type', 'typedef'] },
            { tags: ['param'] },
            { tags: ['property'] },
            { tags: ['param'] },
            { tags: ['see'] },
            { tags: ['example'] },
            { tags: ['throws'] },
            { tags: ['returns'] },
            { tags: ['deprecated'] },
          ],
        },
      ],
      'jsdoc/tag-lines': ['error', 'any', { endLines: 0, startLines: 1 }],
    },
    settings: {
      jsdoc: {
        tagNamePreference: {
          access: false,
          alias: false,
          async: false,
          augments: false,
          author: false,
          borrows: false,
          callback: false,
          class: false,
          classdesc: false,
          constant: false,
          constructs: false,
          copyright: false,
          description: false,
          event: false,
          exports: false,
          external: false,
          file: false,
          fires: false,
          function: false,
          generator: false,
          global: false,
          hideconstructor: false,
          ignore: false,
          implements: false,
          inheritdoc: false,
          inner: false,
          instance: false,
          interface: false,
          kind: false,
          lends: false,
          license: false,
          listens: false,
          member: false,
          memberof: false,
          'memberof!': false,
          mixes: false,
          mixin: false,
          module: false,
          name: false,
          namespace: false,
          override: false,
          package: false,
          private: false,
          protected: false,
          public: false,
          readonly: false,
          requires: false,
          since: false,
          static: false,
          summary: false,
          this: false,
          todo: false,
          tutorial: false,
          variation: false,
          version: false,
          yields: false,
        },
      },
    },
  },
];
