import { type ThemeConfig, type ThemePluginUtils } from './types';

/**
 * Defines the portions of the Tailwind theme that control color, including the palette itself,
 * the per-utility color scales that derive from it and the opacity scales that those colors are
 * modified by.
 */
export const ColorTheme = {
  accentColor: ({ theme }: ThemePluginUtils) => ({
    ...theme('colors'),
    auto: 'auto',
  }),
  backgroundColor: ({ theme }: ThemePluginUtils) => theme('colors'),
  backgroundOpacity: ({ theme }: ThemePluginUtils) => theme('opacity'),
  borderColor: ({ theme }: ThemePluginUtils) => ({
    ...theme('colors'),
    DEFAULT: theme('colors.gray.200', 'currentColor'),
  }),
  borderOpacity: ({ theme }: ThemePluginUtils) => theme('opacity'),
  boxShadowColor: ({ theme }: ThemePluginUtils) => theme('colors'),
  caretColor: ({ theme }: ThemePluginUtils) => theme('colors'),
  colors: ({ colors }) => ({
    amber: colors.amber,
    'app-background': '#fbfbfb',
    black: colors.black,
    blue: {
      '50': '#E7F5FF',
      '100': '#D0EBFF',
      '200': '#A5D8FF',
      '300': '#74C0FC',
      '400': '#4DABF7',
      '500': '#339AF0',
      '600': '#228BE6',
      '700': '#1C7ED6',
      '800': '#1971C2',
      '900': '#1864AB',
    },
    body: '#515151',
    'body-hover': '#404040',
    // Gray 300
    border: '#DEE2E6',
    current: colors.current,
    cyan: colors.cyan,
    danger: {
      '50': '#fef2f2',
      '100': '#fee2e2',
      '200': '#fecaca',
      '300': '#fca5a5',
      '400': '#f87171',
      '500': '#ef4444',
      '600': '#dc2626',
      '700': '#b91c1c',
      '800': '#991b1b',
      '900': '#7f1d1d',
      '950': '#450a0a',
    },
    // Gray 600
    description: '#868E96',
    disabled: '#DEE2E6',
    'disabled-background': '#efefef',
    'disabled-border': '#f5f5f5',
    emerald: colors.emerald,
    fuchsia: colors.fuchsia,
    'github-black': '#1f2328',
    'github-gray': '#636c76',
    gray: {
      '50': '#F8F9FA',
      '100': '#F1F3F5',
      '200': '#E9ECEF',
      '300': '#DEE2E6',
      '400': '#CED4DA',
      '500': '#ADB5BD',
      '600': '#868E96',
      '700': '#495057',
      '800': '#343A40',
      '900': '#212529',
    },
    green: colors.green,
    indigo: colors.indigo,
    inherit: colors.inherit,
    label: '#6a6a6a',
    'label-dark': '#515151',
    lime: colors.lime,
    neutral: colors.neutral,
    'npm-red': '#ea2039',
    orange: colors.orange,
    pink: colors.pink,
    placeholder: 'rgba(96, 104, 115, 0.6)',
    primary: '#4989e4',
    purple: colors.purple,
    red: colors.red,
    rose: colors.rose,
    sky: colors.sky,
    slate: colors.slate,
    stone: colors.stone,
    teal: colors.teal,
    title: '#111827',
    transparent: colors.transparent,
    violet: colors.violet,
    white: colors.white,
    yellow: colors.yellow,
    zinc: colors.zinc,
  }),
  divideColor: ({ theme }: ThemePluginUtils) => theme('borderColor'),
  divideOpacity: ({ theme }: ThemePluginUtils) => theme('borderOpacity'),
  fill: ({ theme }: ThemePluginUtils) => ({
    none: 'none',
    ...theme('colors'),
  }),
  gradientColorStopPositions: {
    '0%': '0%',
    '5%': '5%',
    '10%': '10%',
    '15%': '15%',
    '20%': '20%',
    '25%': '25%',
    '30%': '30%',
    '35%': '35%',
    '40%': '40%',
    '45%': '45%',
    '50%': '50%',
    '55%': '55%',
    '60%': '60%',
    '65%': '65%',
    '70%': '70%',
    '75%': '75%',
    '80%': '80%',
    '85%': '85%',
    '90%': '90%',
    '95%': '95%',
    '100%': '100%',
  },
  gradientColorStops: ({ theme }: ThemePluginUtils) => theme('colors'),
  opacity: {
    0: '0',
    5: '0.05',
    10: '0.1',
    15: '0.15',
    20: '0.2',
    25: '0.25',
    30: '0.3',
    35: '0.35',
    40: '0.4',
    45: '0.45',
    50: '0.5',
    55: '0.55',
    60: '0.6',
    65: '0.65',
    70: '0.7',
    75: '0.75',
    80: '0.8',
    85: '0.85',
    90: '0.9',
    95: '0.95',
    100: '1',
  },
  outlineColor: ({ theme }: ThemePluginUtils) => theme('colors'),
  placeholderColor: ({ theme }: ThemePluginUtils) => theme('colors'),
  placeholderOpacity: ({ theme }: ThemePluginUtils) => theme('opacity'),
  ringColor: ({ theme }: ThemePluginUtils) => ({
    DEFAULT: theme('colors.blue.900', '#3b82f6'),
    ...theme('colors'),
  }),
  ringOffsetColor: ({ theme }: ThemePluginUtils) => theme('colors'),
  ringOpacity: ({ theme }: ThemePluginUtils) => ({
    DEFAULT: '0.5',
    ...theme('opacity'),
  }),
  stroke: ({ theme }: ThemePluginUtils) => ({
    none: 'none',
    ...theme('colors'),
  }),
  textColor: ({ theme }: ThemePluginUtils) => theme('colors'),
  textDecorationColor: ({ theme }: ThemePluginUtils) => theme('colors'),
  textOpacity: ({ theme }: ThemePluginUtils) => theme('opacity'),
} as const satisfies ThemeConfig;
