import { type ThemeConfig, type ThemePluginUtils } from './types';

/**
 * Defines the portions of the Tailwind theme that control visual effects, namely filters,
 * shadows, backgrounds, transforms, transitions and animations.
 */
export const EffectTheme = {
  animation: {
    bounce: 'bounce 1s infinite',
    none: 'none',
    ping: 'ping 1s cubic-bezier(0, 0, 0.2, 1) infinite',
    pulse: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
    spin: 'spin 1s linear infinite',
  },
  backdropBlur: ({ theme }: ThemePluginUtils) => theme('blur'),
  backdropBrightness: ({ theme }: ThemePluginUtils) => theme('brightness'),
  backdropContrast: ({ theme }: ThemePluginUtils) => theme('contrast'),
  backdropGrayscale: ({ theme }: ThemePluginUtils) => theme('grayscale'),
  backdropHueRotate: ({ theme }: ThemePluginUtils) => theme('hueRotate'),
  backdropInvert: ({ theme }: ThemePluginUtils) => theme('invert'),
  backdropOpacity: ({ theme }: ThemePluginUtils) => theme('opacity'),
  backdropSaturate: ({ theme }: ThemePluginUtils) => theme('saturate'),
  backdropSepia: ({ theme }: ThemePluginUtils) => theme('sepia'),
  backgroundImage: {
    'gradient-to-b': 'linear-gradient(to bottom, var(--tw-gradient-stops))',
    'gradient-to-bl': 'linear-gradient(to bottom left, var(--tw-gradient-stops))',
    'gradient-to-br': 'linear-gradient(to bottom right, var(--tw-gradient-stops))',
    'gradient-to-l': 'linear-gradient(to left, var(--tw-gradient-stops))',
    'gradient-to-r': 'linear-gradient(to right, var(--tw-gradient-stops))',
    'gradient-to-t': 'linear-gradient(to top, var(--tw-gradient-stops))',
    'gradient-to-tl': 'linear-gradient(to top left, var(--tw-gradient-stops))',
    'gradient-to-tr': 'linear-gradient(to top right, var(--tw-gradient-stops))',
    none: 'none',
  },
  backgroundPosition: {
    bottom: 'bottom',
    center: 'center',
    left: 'left',
    'left-bottom': 'left bottom',
    'left-top': 'left top',
    right: 'right',
    'right-bottom': 'right bottom',
    'right-top': 'right top',
    top: 'top',
  },
  backgroundSize: {
    auto: 'auto',
    contain: 'contain',
    cover: 'cover',
  },
  blur: {
    0: '0',
    '2xl': '40px',
    '3xl': '64px',
    DEFAULT: '8px',
    lg: '16px',
    md: '12px',
    none: '0',
    sm: '4px',
    xl: '24px',
  },
  boxShadow: {
    '2xl': '0 25px 50px -12px rgb(0 0 0 / 0.25)',
    DEFAULT: '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
    inner: 'inset 0 2px 4px 0 rgb(0 0 0 / 0.05)',
    lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
    md: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
    none: 'none',
    sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
    xl: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
  },
  brightness: {
    0: '0',
    50: '.5',
    75: '.75',
    90: '.9',
    95: '.95',
    100: '1',
    105: '1.05',
    110: '1.1',
    125: '1.25',
    150: '1.5',
    200: '2',
  },
  contrast: {
    0: '0',
    50: '.5',
    75: '.75',
    100: '1',
    125: '1.25',
    150: '1.5',
    200: '2',
  },
  dropShadow: {
    '2xl': '0 25px 25px rgb(0 0 0 / 0.15)',
    DEFAULT: ['0 1px 2px rgb(0 0 0 / 0.1)', '0 1px 1px rgb(0 0 0 / 0.06)'],
    lg: ['0 10px 8px rgb(0 0 0 / 0.04)', '0 4px 3px rgb(0 0 0 / 0.1)'],
    md: ['0 4px 3px rgb(0 0 0 / 0.07)', '0 2px 2px rgb(0 0 0 / 0.06)'],
    none: '0 0 #0000',
    sm: '0 1px 1px rgb(0 0 0 / 0.05)',
    xl: ['0 20px 13px rgb(0 0 0 / 0.03)', '0 8px 5px rgb(0 0 0 / 0.08)'],
  },
  grayscale: {
    0: '0',
    DEFAULT: '100%',
  },
  hueRotate: {
    0: '0deg',
    15: '15deg',
    30: '30deg',
    60: '60deg',
    90: '90deg',
    180: '180deg',
  },
  invert: {
    0: '0',
    DEFAULT: '100%',
  },
  keyframes: {
    bounce: {
      '0%, 100%': {
        animationTimingFunction: 'cubic-bezier(0.8,0,1,1)',
        transform: 'translateY(-25%)',
      },
      '50%': {
        animationTimingFunction: 'cubic-bezier(0,0,0.2,1)',
        transform: 'none',
      },
    },
    ping: {
      '75%, 100%': {
        opacity: '0',
        transform: 'scale(2)',
      },
    },
    pulse: {
      '50%': {
        opacity: '.5',
      },
    },
    spin: {
      to: {
        transform: 'rotate(360deg)',
      },
    },
  },
  rotate: {
    0: '0deg',
    1: '1deg',
    2: '2deg',
    3: '3deg',
    6: '6deg',
    12: '12deg',
    45: '45deg',
    90: '90deg',
    180: '180deg',
  },
  saturate: {
    0: '0',
    50: '.5',
    100: '1',
    150: '1.5',
    200: '2',
  },
  scale: {
    0: '0',
    50: '.5',
    75: '.75',
    90: '.9',
    95: '.95',
    100: '1',
    105: '1.05',
    110: '1.1',
    125: '1.25',
    150: '1.5',
  },
  sepia: {
    0: '0',
    DEFAULT: '100%',
  },
  skew: {
    0: '0deg',
    1: '1deg',
    2: '2deg',
    3: '3deg',
    6: '6deg',
    12: '12deg',
  },
  transformOrigin: {
    bottom: 'bottom',
    'bottom-left': 'bottom left',
    'bottom-right': 'bottom right',
    center: 'center',
    left: 'left',
    right: 'right',
    top: 'top',
    'top-left': 'top left',
    'top-right': 'top right',
  },
  transitionDelay: {
    0: '0s',
    75: '75ms',
    100: '100ms',
    150: '150ms',
    200: '200ms',
    300: '300ms',
    500: '500ms',
    700: '700ms',
    1000: '1000ms',
  },
  transitionDuration: {
    0: '0s',
    75: '75ms',
    100: '100ms',
    150: '150ms',
    200: '200ms',
    300: '300ms',
    500: '500ms',
    700: '700ms',
    1000: '1000ms',
    DEFAULT: '150ms',
  },
  transitionProperty: {
    all: 'all',
    colors: 'color, background-color, border-color, text-decoration-color, fill, stroke',
    DEFAULT:
      'color, background-color, border-color, text-decoration-color, fill, stroke, opacity, ' +
      'box-shadow, transform, filter, backdrop-filter',
    none: 'none',
    opacity: 'opacity',
    shadow: 'box-shadow',
    transform: 'transform',
  },
  transitionTimingFunction: {
    DEFAULT: 'cubic-bezier(0.4, 0, 0.2, 1)',
    in: 'cubic-bezier(0.4, 0, 1, 1)',
    'in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
    linear: 'linear',
    out: 'cubic-bezier(0, 0, 0.2, 1)',
  },
  willChange: {
    auto: 'auto',
    contents: 'contents',
    scroll: 'scroll-position',
    transform: 'transform',
  },
} as const satisfies ThemeConfig;
